"""relationships for contact, org, event, event_attendance

Revision ID: 1f5a3948e8fb
Revises: c93ef3bf8b8d
Create Date: 2023-02-08 16:13:41.728197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f5a3948e8fb'
down_revision = 'c93ef3bf8b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('org_ids', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'contact', 'org', ['org_ids'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'org_ids')
    # ### end Alembic commands ###
