"""testing work focus

Revision ID: 2ca115f453fb
Revises: 
Create Date: 2023-02-09 10:31:39.145710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca115f453fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('work_focus', sa.ARRAY(sa.Enum('INDIGENOUS', 'LGBTI', 'REL_FREEDOM', 'WOMENS_RIGHTS', 'OTHER', name='wf', create_constraint=False, native_enum=False)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org', 'work_focus')
    # ### end Alembic commands ###
