"""create relationships

Revision ID: 4950d0255e6d
Revises: f909847a23d2
Create Date: 2023-02-09 15:00:04.720890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4950d0255e6d'
down_revision = 'f909847a23d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'participant_id')
    )
    op.add_column('contact', sa.Column('org_ids', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'contact', 'org', ['org_ids'], ['id'])
    op.add_column('org', sa.Column('foci', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'org', 'work_focus', ['foci'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org', type_='foreignkey')
    op.drop_column('org', 'foci')
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'org_ids')
    op.drop_table('event_attendance')
    # ### end Alembic commands ###
