"""drop event_attendance table to start again

Revision ID: bce2a0195229
Revises: c3d46273acf1
Create Date: 2023-02-12 18:32:04.445056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bce2a0195229'
down_revision = 'c3d46273acf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('event_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('participant_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('attended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_attendance_event_id_fkey'),
    sa.ForeignKeyConstraint(['participant_id'], ['contact.id'], name='event_attendance_participant_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', 'participant_id', name='event_attendance_pkey')
    )
    # ### end Alembic commands ###
