"""initialize event attendance

Revision ID: c3d46273acf1
Revises: c66398b87256
Create Date: 2023-02-12 15:06:01.380075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3d46273acf1'
down_revision = 'c66398b87256'
branch_labels = None
depends_on = 'c66398b87256'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'participant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_attendance')
    # ### end Alembic commands ###
