"""setting up relationships

Revision ID: d182bd813065
Revises: 4f3c3be0bc84
Create Date: 2023-02-08 19:42:40.795427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd182bd813065'
down_revision = '4f3c3be0bc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'participant_id')
    )
    op.add_column('contact', sa.Column('org_ids', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'contact', 'org', ['org_ids'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'org_ids')
    op.drop_table('event_attendance')
    # ### end Alembic commands ###
