"""initial model setup including work_focus model

Revision ID: d1bc928fafd8
Revises: 
Create Date: 2023-02-09 11:55:09.108696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1bc928fafd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_focus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('org', 'work_focus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org', sa.Column('work_focus', postgresql.ARRAY(sa.VARCHAR(length=13)), autoincrement=False, nullable=True))
    op.drop_table('work_focus')
    # ### end Alembic commands ###
