"""initial setup

Revision ID: d5e6b2a521b1
Revises: 
Create Date: 2023-02-13 04:53:47.324951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5e6b2a521b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'NONBINARY', 'OTHER', 'UNKNOWN', name='gender'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('CONFERENCE', 'FORUM', 'MEETING', 'TA', 'TRAINING', 'OTHER', name='eventtype'), nullable=True),
    sa.Column('subjects', sa.ARRAY(sa.Enum('ACCOUNTING', 'ANTI_CORR_GEN', 'ANTI_CORR_FOR_ACC', 'ANTI_CORR_MON_GOV', 'ANTI_CORR_MON_STA', 'ANTI_CORR_PROCURE', 'CIV_ED', 'CONFLICT_MED', 'CONFLICT_RES', 'CONSENSUS_BUILD', 'OTHER', name='subject')), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('org_sector', sa.Enum('ACADEMIA', 'NGO', 'GOVT', 'MEDIA', 'BUSINESS', 'CSR', 'SOC_ENT', 'IDP', 'OTHER', name='orgsector'), nullable=True),
    sa.Column('foci', sa.ARRAY(sa.Enum('INDIGENOUS', 'LGBTI', 'REL_FREEDOM', 'WOMENS_RIGHTS', 'OTHER', name='wf')), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('con_org',
    sa.Column('org_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contact_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('con_org')
    op.drop_table('org')
    op.drop_table('indicator')
    op.drop_table('event')
    op.drop_table('contact')
    # ### end Alembic commands ###
