"""initialize con_org

Revision ID: e6fb6f4dfdd6
Revises: f7796f16c80a
Create Date: 2023-02-13 02:17:56.171055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6fb6f4dfdd6'
down_revision = 'f7796f16c80a'
branch_labels = None
depends_on = 'c66398b87256'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('con_org',
    sa.Column('org_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contact_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('org_id', 'contact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('con_org')
    # ### end Alembic commands ###
