"""removing event_attendance

Revision ID: f7796f16c80a
Revises: 65a22ae61c9f
Create Date: 2023-02-13 02:13:09.242396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7796f16c80a'
down_revision = '65a22ae61c9f'
branch_labels = None
depends_on = '65a22ae61c9f'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendance',
    sa.Column('event_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('participant_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('attended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_attendance_event_id_fkey'),
    sa.ForeignKeyConstraint(['participant_id'], ['contact.id'], name='event_attendance_participant_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', 'participant_id', name='event_attendance_pkey')
    )
    # ### end Alembic commands ###
